### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by gleporeNARA** [dhondta/python-codext#7]
Getting this error:

```
$ echo -en "test" | codext encode base64 gzip | codext guess
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/codext", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/codext/__init__.py", line 254, in main
    raise e
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/codext/__init__.py", line 230, in main
    s, lb = args.stop_function, args.lang_backend
                                ^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'lang_backend'
```

Any ideas? I installed codext with pip. Thanks.

**Comment by dhondta** [comment]
Hi @gleporeNARA !
Thank you for mentioning this.
I will check this ASAP and let you know.

**Comment by dhondta** [comment]
@gleporeNARA It seems there is a special case I did not consider.
See [line 146 in `__init__.py`](https://github.com/dhondta/python-codext/blob/main/src/codext/__init__.py#L146) ; if there is no language backend, the list has length 0 and the option does not get added, hence the namespace does not have it.
Therefore, I need to replace at line 230 `args.lang_backend` with `getattr(args, "lang_backend", "none")` to avoid the error.
I will fix it now.

**Comment by gleporeNARA** [comment]
That did it, thanks!

**Comment by dhondta** [comment]
My pleasure 😉
