### ISSUE TITLE
base64 unexpected behavior

### ISSUE THREAD

**Issue by nikaiw** [dhondta/python-codext#8]
Soo I was doing this ctf for which I thought I might need to perform some steg attacks. I ended-up installing StegoLSB which require  tinyscript which require python-codext. BUT *to my mistake* I did this outside of a virtualenv.

Long story short, I eventually had to base64 decode a PDF, which despite my different attempts seemed empty. This was until I realised that  calling base64 -d didn't call the beloved /usr/bin/base64 but the ~/.local/bin/base64 of python-codext.

Now the issue,  

The script seems to be utf8 encoding the output (without reason) and this whether we redirect the output to a file or not. 

As an example I get:
```
head -c 100 /tmp/a|base64 -d|hexdump -C
00000000  25 50 44 46 2d 31 2e 34  0a 31 20 30 20 6f 62 6a  |%PDF-1.4.1 0 obj|
00000010  0a 3c 3c 0a 2f 54 69 74  6c 65 20 28 c3 be c3 bf  |.<<./Title (....|
00000020  29 0a 2f 43 72 65 61 74  6f 72 20 28 c3 be c3 bf  |)./Creator (....|
00000030  00 77 00 6b 00 68 00 74  00 6d 00 6c 00 74 00 6f  |.w.k.h.t.m.l.t.o|
00000040  00 70 00 64 00 66 00 20  00 30 00 2e 00 31 00 0a  |.p.d.f. .0...1..|
```
Instead of the expected:
```
base64.b64decode("JVBERi0xLjQKMSAwIG9iago8PAovVGl0bGUgKP7/KQovQ3JlYXRvciAo/v8AdwBrAGgAdABt")
b'%PDF-1.4\n1 0 obj\n<<\n/Title (\xfe\xff)\n/Creator (\xfe\xff\x00w\x00k\x00h\x00t\x00m'
```

**Comment by dhondta** [comment]
@nikaiw Thank you for reporting. I apologize for the inconvenience ; I know how frustrating it can be in the excitation of a CTF. I will look into this ASAP.

**Comment by dhondta** [comment]
@nikaiw Please wait a few minutes and then Pip-upgrade to v1.15.2. Can you test on your challenge and provide feedback ?

**Comment by dhondta** [comment]
@nikaiw Finally, it should be OK for now. You can pip-upgrade and test.
